
#' Stop an R job
#'
#' `stop_job` stops a job that was started with [run_job_wrapper()].
#' The user must provide the id of the job to stop. This id is automatically
#' generated by `run_job_wrapper`. The id is printed in the output in the Jobs
#' pane in RStudio, and is (invisibly) returned by `run_job_wrapper`.
#'
#' @param id The id of the job to stop
#' @export
stop_job <- function(id) {
  processes <- ps::ps() %>%
    dplyr::filter(username == Sys.getenv("USER"), name == "R") %>%
    dplyr::mutate(
      env = purrr::map(ps_handle, ps::ps_environ),
      job_id = purrr::map_chr(env, ~as.list(.)[["R_JOB_ID"]] %||% NA_character_)
    ) %>%
    dplyr::filter(job_id == id)

  if (nrow(processes) == 0) stop("No running processes with id")
  handle <- processes$ps_handle[[1]]
  ps::ps_interrupt(handle)
  message("Stopped job ", id)
  invisible(0)
}

#' Stop EC2 Instances
#'
#' Stop one or more running EC2 instances by instance id.
#'
#' @param ids Vector or list of ids of instances to stop
#' @param region Region of EC2 instances to stop
#' @export
stop_instances <- function(ids,
                           region) {
  svc_ec2 <- paws::ec2(config = list(region = region))
  svc_ec2$terminate_instances(InstanceIds = as.list(ids))
}


